# Bergische Universität Wuppertal #

**Fakultät Mathematik und Naturwissenschaften** 

**Angewandte Mathematik/Numerische Analysis**




# Computational Finance I



# P1: Trinomial Tree
In the problem we mentioned that a binomial model can be generalized to a trinomial model. In a trinomial model we need to consider three stock price developments: in one period the price increases by a factor of $u$ with the probability $p_u$, descreases by a factor of $d$ with the probability $p_d$, or remains unchanged with the probability $1−p_u −p_d$. The trinomial model can be built in a similar way to the binomial model, e.g., by matching the expectation and the variance and using $ud = 1$ we obtain:
    $$ u = e^{\sigma\sqrt{2\Delta t}}, \quad d = e^{-\sigma\sqrt{2\Delta t}}, \quad p_d = \left( \frac{ e^{\sigma\sqrt{\frac{\Delta t}{2}}} - e^{r\frac{\Delta t}{2}} }{e^{\sigma\sqrt{\frac{\Delta t}{2}}} - e^{-\sigma\sqrt{\frac{\Delta t}{2}}}} \right)^2, \quad \quad p_u = \left( \frac{ e^{r\frac{\Delta t}{2}} - e^{-\sigma\sqrt{\frac{\Delta t}{2}}}}{e^{\sigma\sqrt{\frac{\Delta t}{2}}} - e^{-\sigma\sqrt{\frac{\Delta t}{2}}}} \right)^2.$$

For the programming task I write the corresponding Python functions that are asked in each section below.

## Write your data

In [1]:
print("First Name:Mohammad Tohin ")
print("Sure Name: Bapari")
print("Degree Type: Master") # Bachelor or Master
print("Degree Name: Master of Science in Computer Simulation in Science ") # E.g. Master of Science in Computer Simulation in Science

First Name:Mohammad Tohin 
Sure Name: Bapari
Degree Type: Master
Degree Name: Master of Science in Computer Simulation in Science 


## Import all necessary modules

In [2]:
import math
import numpy as np

## Test Parameters

In [3]:
# Input parameters
sigma = 0.2
K = 100
S0 = 100
N = 4
r = 0.05
T = 1
d_t = T / N

## Define a function to calculate the up and down factors

In [4]:
def calc_ud(sigma, d_t):
    """
    Function that calculates the factors in the trinomial model

    Input: sigma -> volatility 
            d_t  -> time step size

    Output: u -> upward movement
            d -> downward movement

    """
u=math.exp(sigma*(math.sqrt(2*d_t)))
d=math.exp(-sigma*(math.sqrt(2*d_t)))


In [5]:
# Calculate upward and downward movements
print("Expected output: u=%f, d=%f" %(u,d))

Expected output: u=1.151910, d=0.868123


**Expected Output:**
`u = 1.151910, d = 0.868123`

## Define a function to calculate the probabilities in the trinomial model

In [6]:
def calc_prob(r, sigma, d_t):
    """
    Function that calculates the probabilities in the trinomial model

    Input: r     -> interest rate
           sigma -> volatility
           d_t   -> time step size

    Output: p_u -> probability for upward movement
            p_d -> probability for downward movement
            p_m -> probability for no change

    """
m1=math.exp(sigma*(math.sqrt(d_t/2)))
m2=math.exp(-sigma*(math.sqrt(d_t/2)))
n=math.exp(r*d_t/2)
p_u=((n-m2)/(m1-m2))**2
p_d=((m1-n)/(m1-m2))**2
p_m=1-p_u-p_d


In [7]:
# Calculate probabilities
print("Expected output:p_u = %f, p_d = %f,p_m = %f" %(p_u,p_d,p_m))

Expected output:p_u = 0.277334, p_d = 0.224084,p_m = 0.498582


**Expected Output:**
`p_u = 0.277334, p_d = 0.224084, p_m = 0.498582`

## Define a function to calculate the stock prices in the trinomial model

In [8]:
def stock_price_trinom(S0, N, u, d):
    
    """
    Function that calculates the stock prices in the trinomial model
    
    Input: S0 -> Initial Stock Price
           u  -> upward movement
           d  -> downward movement
           N  -> Number of time periods
       
    Output: S -> Upper triangular matrix of Stock prices with tirnomial model
    """
S=np.zeros((2*N+1,N+1))
S[0,0]=S0

for j in range(1,N+1):
     for i in range(0,2*j+1):
        S[i,j]=S0*u**j*d**i
   

In [9]:
# Calculate stock prices
print("\nStock prices\n\n",S)


Stock prices

 [[100.         115.19099102 132.68964411 152.84651603 176.06541655]
 [  0.         100.         115.19099102 132.68964411 152.84651603]
 [  0.          86.81234454 100.         115.19099102 132.68964411]
 [  0.           0.          86.81234454 100.         115.19099102]
 [  0.           0.          75.36383164  86.81234454 100.        ]
 [  0.           0.           0.          75.36383164  86.81234454]
 [  0.           0.           0.          65.42510919  75.36383164]
 [  0.           0.           0.           0.          65.42510919]
 [  0.           0.           0.           0.          56.7970712 ]]


**Expected Output:**

`Stock Prices`

`[[100.         115.19099102 132.68964411 152.84651603 176.06541655]
 [  0.         100.         115.19099102 132.68964411 152.84651603]
 [  0.          86.81234454 100.         115.19099102 132.68964411]
 [  0.           0.          86.81234454 100.         115.19099102]
 [  0.           0.          75.36383164  86.81234454 100.        ]
 [  0.           0.           0.          75.36383164  86.81234454]
 [  0.           0.           0.          65.42510919  75.36383164]
 [  0.           0.           0.           0.          65.42510919]
 [  0.           0.           0.           0.          56.7970712 ]]`

## Define a function to calculate the European option price using trinomial model

In [10]:
def priceTriEuro(N, K, r, S, p_u, p_d, p_m, d_t):
    """
    Function that calculates the European option price using trinomial model
    
    Input: N     -> Number of time periods
           K     -> Strike price
           r     -> Interst rate
           S     -> Upper triangular matrix
           p_u   -> probability for upward movement
           p_d   -> probability for downward movement
           p_m   -> probability for no change
           d_t   -> time step size
       
    Output: C -> European Call option 
            P -> European Put option 

    """
EC=np.zeros((2*N+1,N+1))
EC[:, N] = np.maximum(np.zeros(2*N + 1), (S[:, N] - K)) 

for j in range(N-1, -1, -1):
    for i in range(0, 2*j+1):
        EC[i,j] = np.exp(-r*d_t)*(p_u * EC[i, j + 1] + p_m *EC[i+1, j+1 ]+p_d*EC[i+2,j+1])        

EP=np.zeros((2*N+1,N+1))
EP[:, N] = np.maximum(np.zeros(2*N + 1), (K-S[:, N])) 

for j in range(N-1, -1, -1):
    for i in range(0, 2*j+1):
        EP[i,j] = np.exp(-r*d_t)*(p_u * EP[i, j + 1] + p_m * EP[i+1, j+1 ]+p_d*EP[i+2,j+1])  


In [11]:
# Calculate European call and put values
print('\nEuropean Call\n\n',EC)
print('\nEuropean Put\n\n',EP)


European Call

 [[10.20509942 20.0925775  35.15865291 54.08873598 76.06541655]
 [ 0.          8.49087322 18.30584772 33.93186407 52.84651603]
 [ 0.          2.35495086  6.54953395 16.43321097 32.68964411]
 [ 0.          0.          1.13955621  4.16064756 15.19099102]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]]

European Put

 [[ 5.32804187  1.22102826  0.          0.          0.        ]
 [ 0.          4.810315    0.64584791  0.          0.        ]
 [ 0.         11.86204809  4.08052515  0.          0.        ]
 [ 0.          0.         11.85820287  2.91842761  0.        ]
 [ 0.          0.         22.16715956 11.94543551  0.        ]
 [ 0.          0.          0.         23.39394841 13.18765546]
 [ 0.          0.    

**Expected Output:**

`European Call`

`[[10.20509942 20.0925775  35.15865291 54.08873598 76.06541655]
 [ 0.          8.49087322 18.30584772 33.93186407 52.84651603]
 [ 0.          2.35495086  6.54953395 16.43321097 32.68964411]
 [ 0.          0.          1.13955621  4.16064756 15.19099102]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]]`

`European Put`

`[[ 5.32804187  1.22102826  0.          0.          0.        ]
 [ 0.          4.810315    0.64584791  0.          0.        ]
 [ 0.         11.86204809  4.08052515  0.          0.        ]
 [ 0.          0.         11.85820287  2.91842761  0.        ]
 [ 0.          0.         22.16715956 11.94543551  0.        ]
 [ 0.          0.          0.         23.39394841 13.18765546]
 [ 0.          0.          0.         33.33267086 24.63616836]
 [ 0.          0.          0.          0.         34.57489081]
 [ 0.          0.          0.          0.         43.2029288 ]]`

## Define a function to calculate the American option price using trinomial model

In [12]:
def priceTriAmer(N, K, r, S, p_u, p_d, p_m, d_t):
    """
    Function that calculates the American option price using trinomial model
    
    Input: N     -> Number of time periods
           K     -> Strike price
           r     -> Interst rate
           S     -> Upper triangular matrix
           p_u   -> probability for upward movement
           p_d   -> probability for downward movement
           p_m   -> probability for no change
           d_t   -> time step size
       
    Output: C -> American Call option 
            P -> American Put option 

    """
AC=np.zeros((2*N+1,N+1))
AC[:, N] = np.maximum(np.zeros(2*N + 1), (S[:, N] - K)) 

for j in range(N-1, -1, -1):
    for i in range(0, 2*j+1):
        AC[i,j] = np.maximum(S[i,j]-K,np.exp(-r*d_t)*(p_u * AC[i, j + 1] + p_m *AC[i+1, j+1 ]+p_d*AC[i+2,j+1]))
     
AP=np.zeros((2*N+1,N+1))
AP[:,N] = np.maximum(np.zeros(2*N + 1), (K-S[:, N]))

for j in range(N-1, -1, -1):
    for i in range(0, 2*j+1):
        AP[i,j] =np.maximum(K-S[i,j],np.exp(-r*d_t)*(p_u * AP[i, j + 1] + p_m * AP[i+1, j+1 ]+p_d*AP[i+2,j+1]))
     

In [13]:
# Calculate American call and put values
print('American Call\n\n',AC)
print('\nAmerican Put\n\n',AP)

American Call

 [[10.20509942 20.0925775  35.15865291 54.08873598 76.06541655]
 [ 0.          8.49087322 18.30584772 33.93186407 52.84651603]
 [ 0.          2.35495086  6.54953395 16.43321097 32.68964411]
 [ 0.          0.          1.13955621  4.16064756 15.19099102]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]]

American Put

 [[ 5.84957502  1.28186433  0.          0.          0.        ]
 [ 0.          5.23988204  0.64584791  0.          0.        ]
 [ 0.         13.18765546  4.35542837  0.          0.        ]
 [ 0.          0.         13.18765546  2.91842761  0.        ]
 [ 0.          0.         24.63616836 13.18765546  0.        ]
 [ 0.          0.          0.         24.63616836 13.18765546]
 [ 0.          0.     

**Expected Output:**

`American Call`

`[[10.20509942 20.0925775  35.15865291 54.08873598 76.06541655]
 [ 0.          8.49087322 18.30584772 33.93186407 52.84651603]
 [ 0.          2.35495086  6.54953395 16.43321097 32.68964411]
 [ 0.          0.          1.13955621  4.16064756 15.19099102]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.        ]]`

`American Put`

`[[ 5.84957502  1.28186433  0.          0.          0.        ]
 [ 0.          5.23988204  0.64584791  0.          0.        ]
 [ 0.         13.18765546  4.35542837  0.          0.        ]
 [ 0.          0.         13.18765546  2.91842761  0.        ]
 [ 0.          0.         24.63616836 13.18765546  0.        ]
 [ 0.          0.          0.         24.63616836 13.18765546]
 [ 0.          0.          0.         34.57489081 24.63616836]
 [ 0.          0.          0.          0.         34.57489081]
 [ 0.          0.          0.          0.         43.2029288 ]]`

## Comparing European and American option values calculated with Trinomial Model from the exact Solution

In [14]:
# Calculate European and American put values for different N and compare to exact solution
# Exact Values
E_P_ex = 5.5735
A_P_ex = 6.0624
N=[4,16,64,256,512,1024]


**Expected Output:**
![title](trinom_tree.png)